added: wireless default unit
qdbp/py9status pull request #9
Opened 2016-09-13 19:35 UTC by vht610

#4
Preliminary wireless unit.
Future development on displaying ip to be considered.

2016-09-15 16:14 UTC, qdbp commented
I would encourage the direct use of /sys/ and /proc/ over requiring binaries, both for performance and compatibility. 

One of the (hitherto unstated) stretch goals for this project is to have no binary blob dependencies (with the exception of units like PY3NVGPU which monitor a proprietary subsystem).

2016-09-15 18:26 UTC, vht610 commented
Further development will migrate towards reading from /sys/ and /proc/. In it's current form I think of it as a placeholder unit that returns the intended outcome (mostly for my own uses) that I thought was stable enough to merge to master despite requiring dependencies.

2016-09-15 18:51 UTC, vht610 commented
The [arch wiki](https://wiki.archlinux.org/index.php/Wireless_network_configuration#Manual_setup) also seems to suggest that these packages are the standard for managing wireless networks, so from a compatibility side I think it would be safe. Though it does mention:

>  wireless_tools - _currently deprecated, but still widely supported._

Perhaps updating to depend on `iw` would be better future-proofing.

2016-09-20 15:04 UTC, qdbp commented on py3s_default_units.py
> +    def __init__(self, *args, wlan_id='wlp2s0', **kwargs):
Do not guess wlan id. It should be a positional argument.

2016-09-20 15:05 UTC, qdbp commented on py3s_default_units.py
> +        iw (probably?)
Ascertain which ones.

2016-09-20 15:06 UTC, qdbp requested changes

2016-09-23 00:44 UTC, qdbp commented
Please separate the `get_chunk` method into `read` and `format`, as per the new API.

2016-10-17 18:33 UTC, qdbp requested changes
highlighted some problems

2016-10-17 18:33 UTC, qdbp commented on src/py3s_default_units.py
> +        'status': up, down, none
please add type prefixes, i.e. 'SSID -> s_SSID', etc

2016-10-17 18:33 UTC, qdbp commented on src/py3s_default_units.py
>          raw_SSID = findall('ESSID:"(.*?)"', out)[0]
does this add a leading space to the returned value of SSID?

2016-10-17 18:33 UTC, qdbp commented on src/py3s_default_units.py
> +        output['quality'] = "{:3.0f}%".format(raw_quality)
should output raw floats, not formatted strings; formatting is `format`'s job!

2016-10-28 15:12 UTC, qdbp requested changes

2016-10-28 15:12 UTC, qdbp commented on src/py3s_default_units.py
> +        's_SSID'
be more descriptive: SSID of what? the currently connected-to network? one with the strongest signal? etc.

2016-10-28 15:12 UTC, qdbp commented on src/py3s_default_units.py
> +        self.wlan_id=wlan_id
PEP8. (applies in other places too)

2016-10-28 15:12 UTC, qdbp commented on src/py3s_default_units.py
> +        output = {'s_status': "up", "s_SSID": "SSID", "f_quality": 0}
"SSID" is a silly default. I recommend following the convention of the other unit and introducing some `b_` error flags for when this unit's output is not applicable; i.e. there is no connection.

2016-11-08 01:05 UTC, merged